{{- if .Values.pdb.enabled | default false -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "piontec-kratix-1.fullname" . }}
  labels:
    {{- include "piontec-kratix-1.labels" . | nindent 4 }}
spec:
  minAvailable: 2
  selector:
    matchLabels:
      {{- include "piontec-kratix-1.selectorLabels" . | nindent 6 }}
{{- end }}
