{{- if .Values.pdb.enabled | default false -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "idp-demo-app.fullname" . }}
  labels:
    {{- include "idp-demo-app.labels" . | nindent 4 }}
spec:
  minAvailable: 2
  selector:
    matchLabels:
      {{- include "idp-demo-app.selectorLabels" . | nindent 6 }}
{{- end }}
