{{- if .Values.monitoring.serviceMonitor.enabled | default false -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "idp-demo-app.fullname" . }}
  labels:
    {{- include "idp-demo-app.labels" . | nindent 4 }}
spec:
  endpoints:
  - path: /metrics
    port: http
  selector:
    matchLabels:
      {{- include "idp-demo-app.selectorLabels" . | nindent 4 }}
{{- end }}
