{{- if .Values.monitoring.serviceMonitor.enabled | default false -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "piontec-kratix-1.fullname" . }}
  labels:
    {{- include "piontec-kratix-1.labels" . | nindent 4 }}
spec:
  endpoints:
  - path: /metrics
    port: http
  selector:
    matchLabels:
      {{- include "piontec-kratix-1.selectorLabels" . | nindent 4 }}
{{- end }}
